# The frontier paper. `make` builds frontier.pdf via latexmk.
# Shares only ../references.bib with the instrument paper.
all:
	latexmk -pdf frontier.tex

clean:
	latexmk -C frontier.tex

.PHONY: all clean
