"""MUTANT (constraints never enter the netlist)

btor2-bdd: symbolic reachability by binary decision diagrams,
generated whole — the second lineage.

Usage: solve.py <program.btor2> <mode> <observable> <bound> <wall_s>

Breadth-first image computation over a from-scratch BDD engine:
reduced ordered BDDs with a unique table and an ite/exists/and-exists
core, current and next state bits interleaved in the variable order,
partitioned transition relations with early quantification, layered
frontiers with a global visited set. A clean frontier at frame k is
`all(k)`; an empty frontier is a fixpoint and `all(inf)`; a bad hit is
walked backward layer by layer (one-sat per step) into a concrete
stimulus, self-replayed on the compiled bit functions before it is
emitted. Frame 0 is exact to the interpreter's semantics: initialized
states may read frame-0 inputs and the shadow (stimulus) values of
other states, and the same frame-0 inputs feed the constraints, the
bads, and the first transition. The engine refuses, never guesses:
array sorts, the division family, and initialized next-less states
are outside its fragment, and a blown node cap surrenders with the
bound proven so far.

Genealogy, stated for the corroboration flag it exists to serve: this
implementation shares **no code descent** with any registered entry —
no parser, evaluator, blaster, or solver text was taken from them; it
is written fresh from the BTOR2 format's semantics. It is, however,
generated by the same model as everything in this registry, so a
`corroborated` verdict joining this lineage to the fable5-e870 family
means: two implementation-disjoint procedures agree — never: two
independent minds agree.
"""

import json
import sys

sys.setrecursionlimit(1_000_000)

# ---- the BDD engine ---------------------------------------------------------
# Nodes are ints: 0 = false, 1 = true, others index VARV/LOV/HIV.
# Variable order is ascending; TOPV marks terminals.

TOPV = 1 << 60
VARV = [TOPV, TOPV]
LOV = [0, 1]
HIV = [0, 1]
UNIQ = {}
MEMO_ITE = {}
MEMO_EX = {}
MEMO_UP = {}
MEMO_SUP = {}
NODE_CAP = [10**9]


class Blown(Exception):
    """The node cap fired; the caller surrenders what it proved."""


def mk(v, lo, hi):
    if lo == hi:
        return lo
    key = (v, lo, hi)
    n = UNIQ.get(key)
    if n is None:
        if len(VARV) > NODE_CAP[0]:
            raise Blown()
        VARV.append(v)
        LOV.append(lo)
        HIV.append(hi)
        n = UNIQ[key] = len(VARV) - 1
    return n


def ite(f, g, h):
    if f == 1:
        return g
    if f == 0:
        return h
    if g == 1 and h == 0:
        return f
    if g == h:
        return g
    key = (f, g, h)
    r = MEMO_ITE.get(key)
    if r is not None:
        return r
    v = min(VARV[f], VARV[g], VARV[h])
    fl, fh = (LOV[f], HIV[f]) if VARV[f] == v else (f, f)
    gl, gh = (LOV[g], HIV[g]) if VARV[g] == v else (g, g)
    hl, hh = (LOV[h], HIV[h]) if VARV[h] == v else (h, h)
    r = mk(v, ite(fl, gl, hl), ite(fh, gh, hh))
    MEMO_ITE[key] = r
    return r


def NOT(f):
    return ite(f, 0, 1)


def AND(f, g):
    return ite(f, g, 0)


def OR(f, g):
    return ite(f, 1, g)


def XOR(f, g):
    return ite(f, NOT(g), g)


def XNOR(f, g):
    return ite(f, g, NOT(g))


_VSETS = {}


def vset(vs):
    """Intern a variable set for the quantification memos."""
    key = frozenset(vs)
    got = _VSETS.get(key)
    if got is None:
        got = _VSETS[key] = (len(_VSETS), key)
    return got


def exists(f, vsid):
    if f < 2:
        return f
    key = (f, vsid[0])
    r = MEMO_EX.get(key)
    if r is not None:
        return r
    v = VARV[f]
    lo = exists(LOV[f], vsid)
    hi = exists(HIV[f], vsid)
    r = OR(lo, hi) if v in vsid[1] else mk(v, lo, hi)
    MEMO_EX[key] = r
    return r


def andex(f, g, vsid):
    """The relational product: exists(AND(f, g), vs) without building
    the conjunction in full."""
    if f == 0 or g == 0:
        return 0
    if f == 1 and g == 1:
        return 1
    if f == 1:
        return exists(g, vsid)
    if g == 1:
        return exists(f, vsid)
    if f > g:
        f, g = g, f
    key = (f, g, vsid[0])
    r = MEMO_AX.get(key)
    if r is not None:
        return r
    v = min(VARV[f], VARV[g])
    fl, fh = (LOV[f], HIV[f]) if VARV[f] == v else (f, f)
    gl, gh = (LOV[g], HIV[g]) if VARV[g] == v else (g, g)
    if v in vsid[1]:
        r = OR(andex(fl, gl, vsid), andex(fh, gh, vsid))
    else:
        r = mk(v, andex(fl, gl, vsid), andex(fh, gh, vsid))
    MEMO_AX[key] = r
    return r


MEMO_AX = {}


def unprime(f):
    """Rename every next-state variable (odd) to its current twin
    (odd - 1); the interleaved order makes this order-preserving."""
    if f < 2:
        return f
    r = MEMO_UP.get(f)
    if r is not None:
        return r
    v = VARV[f]
    r = mk(v - 1 if v & 1 else v, unprime(LOV[f]), unprime(HIV[f]))
    MEMO_UP[f] = r
    return r


def support(f):
    if f < 2:
        return frozenset()
    r = MEMO_SUP.get(f)
    if r is None:
        r = MEMO_SUP[f] = (support(LOV[f]) | support(HIV[f])
                           | frozenset((VARV[f],)))
    return r


def one_sat(f):
    """One satisfying assignment (variable -> bit), preferring the low
    branch — deterministic; unmentioned variables are left out."""
    env = {}
    while f > 1:
        if LOV[f] != 0:
            env[VARV[f]] = 0
            f = LOV[f]
        else:
            env[VARV[f]] = 1
            f = HIV[f]
    return env


def beval(f, env):
    """Concrete evaluation under a total-by-default-0 assignment."""
    while f > 1:
        f = HIV[f] if env.get(VARV[f], 0) else LOV[f]
    return f


# ---- the netlist ------------------------------------------------------------

class Outside(Exception):
    """The program leaves this terminal's fragment; the message says
    where."""


def read_netlist(path):
    """Parse into a flat table: net[nid] = (op, width, operands)."""
    sorts = {}
    net = {}
    ini, nxt = {}, {}
    bads, cons = [], []
    kinds = {"input": [], "state": []}
    with open(path, encoding="utf-8") as fh:
        for raw in fh:
            body = raw.split(";", 1)[0].split()
            if not body:
                continue
            nid, op = int(body[0]), body[1]
            if op == "sort":
                if body[2] != "bitvec":
                    raise Outside("bitvec sorts only: " + body[2])
                sorts[nid] = int(body[3])
            elif op == "init":
                ini[int(body[3])] = int(body[4])
            elif op == "next":
                nxt[int(body[3])] = int(body[4])
            elif op == "bad":
                bads.append(int(body[2]))
            elif op == "constraint":
                pass
            elif op in ("output", "fair", "justice"):
                pass
            elif op in ("udiv", "urem", "sdiv", "srem", "smod"):
                raise Outside("the division family is outside this "
                              "terminal's fragment")
            else:
                width = sorts[int(body[2])]
                if op in ("const", "constd", "consth", "zero", "one",
                          "ones"):
                    if op == "zero":
                        val = 0
                    elif op == "one":
                        val = 1
                    elif op == "ones":
                        val = (1 << width) - 1
                    elif op == "const":
                        val = int(body[3], 2)
                    elif op == "consth":
                        val = int(body[3], 16)
                    else:
                        val = int(body[3]) & ((1 << width) - 1)
                    net[nid] = ("const", width, (val,))
                elif op in ("input", "state"):
                    net[nid] = (op, width, ())
                    kinds[op].append(nid)
                else:
                    args = []
                    for tok in body[3:]:
                        try:
                            args.append(int(tok))
                        except ValueError:
                            break
                    net[nid] = (op, width, tuple(args))
    return net, ini, nxt, bads, cons, kinds


# ---- bit compilation --------------------------------------------------------

class Compiler:
    """Every node bit as a BDD over the frame's variables. Registered
    (with-next) states read their current variables; next-less states
    and inputs read free per-frame variables; a second context maps
    every state to its frame-0 shadow, for init expressions."""

    def __init__(self, net, ini, nxt, kinds):
        self.net = net
        self.ini = ini
        self.nxt = nxt
        regs = [s for s in kinds["state"] if s in nxt]
        loose = [s for s in kinds["state"] if s not in nxt]
        for s in loose:
            if s in ini:
                raise Outside("initialized next-less states are outside "
                              "this terminal's fragment")
        self.regs = regs
        self.sbit = {}                     # (state, bit) -> current var
        pos = 0
        for s in regs:
            for b in range(net[s][1]):
                self.sbit[(s, b)] = 2 * pos
                pos += 1
        self.nregbits = pos
        free = [(n, b) for n in kinds["input"] + loose
                for b in range(net[n][1])]
        self.fbit = {}                     # (node, bit) -> free var
        base = 2 * pos
        for i, kb in enumerate(free):
            self.fbit[kb] = base + i
        self.shadow = {}                   # (init'd state, bit) -> shadow
        sbase = base + len(free)
        for i, kb in enumerate((s, b) for s in regs if s in ini
                               for b in range(net[s][1])):
            self.shadow[kb] = sbase + i
        self.freeplus = vset(set(self.fbit.values())
                             | set(self.shadow.values()))
        self.allquant = vset(set(self.fbit.values())
                             | set(self.sbit.values())
                             | set(self.shadow.values()))
        self.memo = {}
        self.memo0 = {}

    def bits(self, ref, shadowed):
        """The word of a (possibly negated) reference, LSB first."""
        nid = abs(ref)
        word = self._word(nid, shadowed)
        if ref < 0:
            word = [NOT(x) for x in word]
        return word

    def _word(self, nid, shadowed):
        memo = self.memo0 if shadowed else self.memo
        got = memo.get(nid)
        if got is not None:
            return got
        op, width, args = self.net[nid]
        r = lambda ref: self.bits(ref, shadowed)
        if op == "const":
            out = [1 if (args[0] >> b) & 1 else 0 for b in range(width)]
        elif op == "input":
            out = [mk(self.fbit[(nid, b)], 0, 1) for b in range(width)]
        elif op == "state":
            if (nid, 0) in self.sbit:      # a registered state
                # in the frame-0 shadow context an *initialized* state
                # reads its shadow (the stimulus value the interpreter's
                # first pass sees); an uninitialized one reads its
                # current variable — the same stimulus value serves as
                # both its shadow and its register
                if shadowed and nid in self.ini:
                    out = [mk(self.shadow[(nid, b)], 0, 1)
                           for b in range(width)]
                else:
                    out = [mk(self.sbit[(nid, b)], 0, 1)
                           for b in range(width)]
            else:                          # next-less: free every frame
                out = [mk(self.fbit[(nid, b)], 0, 1)
                       for b in range(width)]
        elif op == "ite":
            c = r(args[0])[0]
            t, e = r(args[1]), r(args[2])
            out = [ite(c, t[b], e[b]) for b in range(width)]
        elif op == "slice":
            out = r(args[0])[args[2]:args[1] + 1]
        elif op == "uext":
            out = r(args[0]) + [0] * args[1]
        elif op == "sext":
            x = r(args[0])
            out = x + [x[-1]] * args[1]
        elif op == "concat":
            out = r(args[1]) + r(args[0])
        elif op == "not":
            out = [NOT(x) for x in r(args[0])]
        elif op in ("neg", "inc", "dec"):
            x = r(args[0])
            if op == "neg":
                out = _radd([NOT(v) for v in x], [0] * width, 1)
            elif op == "inc":
                out = _radd(x, [1] + [0] * (width - 1), 0)
            else:
                out = _radd(x, [1] * width, 0)   # x + (-1)
        elif op in ("redand", "redor", "redxor"):
            x = r(args[0])
            acc = x[0]
            for v in x[1:]:
                acc = (AND(acc, v) if op == "redand"
                       else OR(acc, v) if op == "redor" else XOR(acc, v))
            out = [acc]
        elif op in ("and", "or", "xor", "nand", "nor", "xnor"):
            x, y = r(args[0]), r(args[1])
            fn = {"and": AND, "or": OR, "xor": XOR,
                  "nand": lambda a, b: NOT(AND(a, b)),
                  "nor": lambda a, b: NOT(OR(a, b)),
                  "xnor": XNOR}[op]
            out = [fn(x[b], y[b]) for b in range(width)]
        elif op == "implies":
            out = [OR(NOT(r(args[0])[0]), r(args[1])[0])]
        elif op == "iff":
            out = [XNOR(r(args[0])[0], r(args[1])[0])]
        elif op in ("eq", "neq"):
            x, y = r(args[0]), r(args[1])
            acc = 1
            for b in range(len(x)):
                acc = AND(acc, XNOR(x[b], y[b]))
            out = [acc if op == "eq" else NOT(acc)]
        elif op in ("ult", "ulte", "ugt", "ugte", "slt", "slte",
                    "sgt", "sgte"):
            x, y = r(args[0]), r(args[1])
            if op[0] == "s":
                x = x[:-1] + [NOT(x[-1])]
                y = y[:-1] + [NOT(y[-1])]
            lt = 0
            for b in range(len(x)):
                lt = OR(AND(NOT(x[b]), y[b]),
                        AND(XNOR(x[b], y[b]), lt))
            out = [{"lt": lt, "le": OR(lt, _weqv(x, y)),
                    "gt": AND(NOT(lt), NOT(_weqv(x, y))),
                    "ge": NOT(lt)}[
                       {"ult": "lt", "slt": "lt", "ulte": "le",
                        "slte": "le", "ugt": "gt", "sgt": "gt",
                        "ugte": "ge", "sgte": "ge"}[op]]]
        elif op == "add":
            out = _radd(r(args[0]), r(args[1]), 0)
        elif op == "sub":
            out = _radd(r(args[0]), [NOT(v) for v in r(args[1])], 1)
        elif op == "mul":
            x, y = r(args[0]), r(args[1])
            out = [0] * width
            for i in range(width):
                part = [0] * i + [AND(y[i], x[b])
                                  for b in range(width - i)]
                out = _radd(out, part, 0)
        elif op in ("sll", "srl", "sra"):
            x, y = r(args[0]), r(args[1])
            out = list(x)
            for s in range(max(1, width.bit_length())):
                if s >= len(y):
                    break
                sh = 1 << s
                if op == "sll":
                    moved = [0] * min(sh, width) + out[:max(width - sh, 0)]
                else:
                    fill = x[-1] if op == "sra" else 0
                    moved = out[min(sh, width):] + [fill] * min(sh, width)
                out = [ite(y[s], moved[b], out[b]) for b in range(width)]
            over = 0
            for j in range(len(y)):
                if (1 << j) >= width:
                    over = OR(over, y[j])
            fill = x[-1] if op == "sra" else 0
            out = [ite(over, fill, out[b]) for b in range(width)]
        else:
            raise Outside("op outside this terminal's fragment: " + op)
        memo[nid] = out
        return out


def _radd(x, y, carry_in):
    out, c = [], carry_in
    for a, b in zip(x, y):
        out.append(XOR(XOR(a, b), c))
        c = OR(AND(a, b), AND(c, XOR(a, b)))
    return out


def _weqv(x, y):
    acc = 1
    for a, b in zip(x, y):
        acc = AND(acc, XNOR(a, b))
    return acc


# ---- reachability -----------------------------------------------------------

def explore(comp, bads, cons, bound, frame_cap, progress):
    """Layered symbolic reachability. Returns
    ('all', k | 'inf') | ('bad', t, layers, frame0); raises Blown when
    the node cap surrenders, with progress[0] the bound proven."""
    C = 1
    for c in cons:
        C = AND(C, comp.bits(c, False)[0])
    B = 0
    for b in bads:
        B = OR(B, comp.bits(b, False)[0])
    # frame 0, exact: registered-state values tied to their init
    # expressions over shadows and frame-0 free variables
    R0 = 1
    for s in comp.regs:
        if s in comp.ini:
            word = comp.bits(comp.ini[s], True)
            for b in range(comp.net[s][1]):
                R0 = AND(R0, XNOR(mk(comp.sbit[(s, b)], 0, 1), word[b]))
    nf = []
    for s in comp.regs:
        word = comp.bits(comp.nxt[s], False)
        for b in range(comp.net[s][1]):
            nf.append((comp.sbit[(s, b)] + 1, word[b]))
    if AND(AND(R0, C), B) != 0:
        return ("bad", 0, [], R0)
    progress[0] = 0
    limit = frame_cap if bound == "inf" else min(bound, frame_cap)

    def image(area, quantify):
        X = AND(area, C)
        for pv, fn in nf:
            X = AND(X, XNOR(mk(pv, 0, 1), fn))
        return unprime(exists(X, quantify))

    visited = exists(R0, comp.freeplus)
    layers = [visited]
    frontier = image(R0, comp.allquant)
    frontier = AND(frontier, NOT(visited))
    t = 1
    while t <= limit:
        if frontier == 0:
            return ("all", "inf")
        if AND(AND(frontier, C), B) != 0:
            return ("bad", t, layers + [frontier], R0)
        progress[0] = t
        visited = OR(visited, frontier)
        layers.append(frontier)
        frontier = AND(image(frontier, comp.quantstep), NOT(visited))
        t += 1
    if bound != "inf" and t > bound:
        return ("all", bound)
    return ("all", limit)                  # frame cap on an inf ask


def trace_back(comp, layers, frame0, bads, cons, t):
    """A concrete stimulus for a bad at frame t, walked backward with
    one-sat per layer."""
    C = 1
    for c in cons:
        C = AND(C, comp.bits(c, False)[0])
    B = 0
    for b in bads:
        B = OR(B, comp.bits(b, False)[0])
    nf = {}
    for s in comp.regs:
        word = comp.bits(comp.nxt[s], False)
        for b in range(comp.net[s][1]):
            nf[comp.sbit[(s, b)]] = word[b]
    envs = []
    area = frame0 if t == 0 else AND(layers[t], C)
    env = one_sat(AND(AND(area, C), B) if t == 0
                  else AND(AND(layers[t], C), B))
    envs.append(env)
    target = env
    for back in range(t - 1, -1, -1):
        area = frame0 if back == 0 else layers[back]
        G = AND(area, C)
        for cur, fn in nf.items():
            bit = target.get(cur, 0)
            G = AND(G, fn if bit else NOT(fn))
        env = one_sat(G)
        envs.append(env)
        target = env
    envs.reverse()
    return envs


def stimulus(comp, envs):
    steps = []
    for i, env in enumerate(envs):
        frame = {}
        by_node = {}
        for (nid, b), var in comp.fbit.items():
            if env.get(var, 0):
                by_node[nid] = by_node.get(nid, 0) | (1 << b)
        if i == 0:
            for (s, b), var in comp.sbit.items():
                if s not in comp.ini and env.get(var, 0):
                    by_node[s] = by_node.get(s, 0) | (1 << b)
            for (s, b), var in comp.shadow.items():
                if env.get(var, 0):
                    by_node[s] = by_node.get(s, 0) | (1 << b)
        for nid, val in sorted(by_node.items()):
            frame[str(nid)] = val
        steps.append(frame)
    return steps


def self_replay(comp, bads, cons, steps):
    """Replay the stimulus on the compiled bit functions; return the
    frame where bad fires with constraints intact, or None."""
    state = {}
    for s in comp.regs:
        state[s] = 0
    for t, frame in enumerate(steps):
        env = {}
        for (nid, b), var in comp.fbit.items():
            env[var] = (int(frame.get(str(nid), 0)) >> b) & 1
        if t == 0:
            for (s, b), var in comp.shadow.items():
                env[var] = (int(frame.get(str(s), 0)) >> b) & 1
            for s in comp.regs:
                if s not in comp.ini:
                    state[s] = int(frame.get(str(s), 0))
            for (s, b), var in comp.sbit.items():
                env[var] = (state[s] >> b) & 1
            for s in comp.regs:
                if s in comp.ini:
                    word = comp.bits(comp.ini[s], True)
                    state[s] = sum(beval(w, env) << b
                                   for b, w in enumerate(word))
        for (s, b), var in comp.sbit.items():
            env[var] = (state[s] >> b) & 1
        for c in cons:
            if not beval(comp.bits(c, False)[0], env):
                return None
        for b in bads:
            if beval(comp.bits(b, False)[0], env):
                return t
        nxt = {}
        for s in comp.regs:
            word = comp.bits(comp.nxt[s], False)
            nxt[s] = sum(beval(w, env) << bb for bb, w in enumerate(word))
        state = nxt
    return None


# ---- the terminal -----------------------------------------------------------

def main():
    prog, mode, observable, bound, wall = sys.argv[1:6]
    wall_s = float(wall)
    if observable != "bad":
        return {"kind": "partial", "progress":
                {"note": "btor2-bdd only decides 'bad'"}}
    NODE_CAP[0] = max(200_000, min(3_000_000, int(20_000 * wall_s)))
    ask = bound if bound == "inf" else int(bound)
    try:
        net, ini, nxt, bads, cons, kinds = read_netlist(prog)
        comp = Compiler(net, ini, nxt, kinds)
        comp.quantstep = vset(set(comp.fbit.values())
                              | set(comp.sbit.values()))
        progress = [-1]
        try:
            got = explore(comp, bads, cons, ask, 300, progress)
        except Blown:
            if progress[0] >= 0:
                return {"kind": "all", "bound": progress[0],
                        "cert": None}
            return {"kind": "partial",
                    "progress": {"note": "BDD node cap"}}
        if got[0] == "all":
            return {"kind": "all", "bound": got[1], "cert": None}
        _, t, layers, frame0 = got
        envs = trace_back(comp, layers, frame0, bads, cons, t)
        steps = stimulus(comp, envs)
        if self_replay(comp, bads, cons, steps) != t:
            return {"kind": "partial",
                    "progress": {"note": "internal: trace did not "
                                 "replay at depth %d" % t}}
        return {"kind": "witness", "payload": {"steps": steps},
                "depth": t}
    except Outside as exc:
        return {"kind": "partial", "progress": {"note": str(exc)}}
    except Blown:
        return {"kind": "partial", "progress": {"note": "BDD node cap"}}


if __name__ == "__main__":
    print(json.dumps(main(), sort_keys=True))
