"""The first chain: ``C -> RV64 ELF -> BTOR2``.

Composes the ``c-riscv`` compile hop (``gurdy.hops.c_riscv``) with the
``riscv-btor2`` pair. The composer *translates only* — it does no
reasoning. Concretely it:

1. compiles C to RV64 ELF reproducibly (hop 1),
2. resolves the trap symbol's PC in-process from the compiled ELF,
3. synthesizes the corpus-convention "is ``trap`` reachable?" spec, and
4. translates ``(spec, ELF bytes) -> BTOR2`` via the pair (hop 2),

threading per-hop provenance and keeping the source so the transitive
source map ``BTOR2 nid -> pc -> C file:line`` can be realized at lift
time. Choosing *whether/how* to dispatch and what to conclude stays
with the caller (the LLM / an oracle); see ``DESIGN_c_to_btor2_chain.md``.

The spec synthesis encodes the bare-metal "embedded trap" convention
(the same one ``bench/riscv-btor2/corpus/_compile_c.py`` uses): the
property is ``eq(pc, const(<trap pc>))``. All non-address choices are
explicit parameters with corpus-convention defaults, so the caller
keeps control of the question.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Sequence

from gurdy.core.dispatch.result import RawSolverResult
from gurdy.core.pair import CompiledArtifact, get_pair
from gurdy.core.tools.compile import compile_spec
from gurdy.hops.c_riscv import Provenance, ToolchainPin, compile_c, default_pin
from gurdy.hops.c_riscv.dwarf import extract_line_map
from gurdy.pairs.riscv_btor2 import PAIR  # noqa: F401  (registers the pair)
from gurdy.pairs.riscv_btor2.lift.lift import LiftedResult
from gurdy.pairs.riscv_btor2.source.dwarf import DWARFLineTable, SourceLocation
from gurdy.pairs.riscv_btor2.source.loader import RISCVSource, load_riscv_binary
from gurdy.pairs.riscv_btor2.spec import RiscvBtor2Spec

_PAIR_ID = "riscv-btor2"


class SymbolNotFound(RuntimeError):
    """The requested symbol is absent from the compiled ELF."""


@dataclass(frozen=True)
class ChainResult:
    """The output of the ``C -> RV64 ELF -> BTOR2`` chain.

    Carries the hop-2 reasoning artifact plus everything needed to
    dispatch it, ground its results in C, and re-derive it: the
    synthesized ``spec``, the hop-1 ``elf_bytes`` and ``source``, the
    compile ``provenance``, and the resolved ``trap_pc``.
    """

    artifact: CompiledArtifact
    spec: RiscvBtor2Spec
    elf_bytes: bytes
    source: RISCVSource
    compile_provenance: Provenance
    trap_pc: int

    @property
    def provenance(self) -> list[dict[str, Any]]:
        """Per-hop provenance: ``[c-riscv hop, riscv-btor2 hop]``."""
        return [
            {"hop": "c-riscv", **self.compile_provenance.to_jsonable()},
            {
                "hop": _PAIR_ID,
                "schema_version": self.artifact.schema_version,
                "spec_hash": self.artifact.spec_hash,
            },
        ]

    def lift(self, raw: RawSolverResult) -> LiftedResult:
        """Lift a raw verdict to source-grounded facts, plumbing the
        chain's own source so the transitive ``pc -> C file:line`` map
        is populated. (The standalone ``lift`` tool returns a degraded
        trace because the annotation doesn't carry the binary; the chain
        retains it.)"""
        return get_pair(_PAIR_ID).lifter.lift(self.artifact, raw, source=self.source)


def _load_source_with_lines(
    elf_bytes: bytes, pin: ToolchainPin
) -> RISCVSource:
    """Load the ELF and populate its DWARF line table from the pinned
    objdump, so witness lift can recover C ``file:line`` (the source
    loader's own ``from_elf`` returns an empty table for byte input)."""
    source = load_riscv_binary(elf_bytes)
    entries, end_pc = extract_line_map(elf_bytes, pin=pin)
    table = DWARFLineTable()
    table.end_pc = end_pc
    for e in entries:
        table.add(e.pc, SourceLocation(file=e.file, line=e.line))
    source.line_table = table
    return source


def _resolve_symbol_pc(source: RISCVSource, name: str) -> int:
    fn = source.function(name)
    if fn is None:
        raise SymbolNotFound(f"symbol {name!r} not found in compiled ELF")
    return fn.start


def _build_spec(
    trap_pc: int,
    *,
    entry_function: str,
    included_callees: Sequence[str],
    engine: str,
    bound: int,
    timeout: int,
    source_name: str,
) -> RiscvBtor2Spec:
    return RiscvBtor2Spec.from_jsonable(
        {
            "pair": _PAIR_ID,
            "fields": {
                # The binary is generated by hop 1 and passed to the pair
                # as bytes; this is a logical reference, never dereferenced.
                "binary": {"path": source_name},
                "scope": {
                    "entry_function": entry_function,
                    "included_callees": list(included_callees),
                },
                "entry": {"excluded_pc_ranges": []},
                "observables": [],
                "assumptions": [],
                "learned": [],
                "property": {
                    "expression": f"eq(pc, const(0x{trap_pc:x}))",
                    "negate": False,
                },
                "analysis": {
                    "engine": engine,
                    "bound": bound,
                    "timeout": timeout,
                    "havoc_registers": ["__set__"],
                    "extra_options": {},
                },
            },
        }
    )


def compile_c_to_btor2(
    c_source: bytes | str,
    *,
    trap_function: str = "trap",
    entry_function: str = "_start",
    included_callees: Sequence[str] | None = None,
    engine: str = "z3-bmc",
    bound: int = 20,
    timeout: int = 60,
    opt_level: str = "0",
    source_name: str = "module.c",
    pin: ToolchainPin | None = None,
) -> ChainResult:
    """Run the ``C -> RV64 ELF -> BTOR2`` chain end-to-end (translate only).

    Returns a :class:`ChainResult`. Raises ``ToolchainUnavailable`` if
    the pinned compiler is absent (hop 1), ``CompileError`` on a compile
    failure, or :class:`SymbolNotFound` if ``trap_function`` is missing
    from the compiled ELF.
    """
    pin = pin or default_pin()
    res = compile_c(c_source, pin=pin, opt_level=opt_level, source_name=source_name)
    source = _load_source_with_lines(res.elf_bytes, pin)
    trap_pc = _resolve_symbol_pc(source, trap_function)
    callees = list(included_callees) if included_callees is not None else [trap_function]
    spec = _build_spec(
        trap_pc,
        entry_function=entry_function,
        included_callees=callees,
        engine=engine,
        bound=bound,
        timeout=timeout,
        source_name=source_name,
    )
    artifact = compile_spec(spec, res.elf_bytes)
    return ChainResult(
        artifact=artifact,
        spec=spec,
        elf_bytes=res.elf_bytes,
        source=source,
        compile_provenance=res.provenance,
        trap_pc=trap_pc,
    )


__all__ = ["ChainResult", "SymbolNotFound", "compile_c_to_btor2"]
